title: Jornadas de Inteligencia Artifical para Analítica Deportiva
description: Web de las Jornadas de Inteligencia Artifical para Analítica Deportiva, 6-7 de noviembre de 2025, UCLM, Albacete
theme: jekyll-theme-minimal
logo: /assets/img/banner.png
google_analytics: 
